name: flatpickr
version: 0.1.1
description: Dart JS interop for flatpickr - a lightweight and powerful datetime picker.

homepage: https://github.com/ganigeorgiev/flatpickr.dart/
repository: https://github.com/ganigeorgiev/flatpickr.dart/

environment:
  sdk: '>=2.12.5 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.1
